name: Chef CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths:
      - 'cookbooks/**'
      - 'kitchen.yml'
      - 'test/**'

jobs:
  test-cookbooks:
    runs-on: ubuntu-latest
    env:
          CHEF_LICENSE: accept-no-persist
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Chef Workstation
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chef-workstation

      - name: Install kitchen-docker
        run: sudo /opt/chef-workstation/embedded/bin/gem install kitchen-docker

      - name: Set up kitchen-docker
        run: |
            echo 'eval "$(chef shell-init bash)"' >> ~/.bashrc
            source ~/.bashrc
            chef gem install kitchen-docker
      - name: Run Test Kitchen
        run: |
          mv kitchen.yml .kitchen.yml
          echo 'eval "$(chef shell-init bash)"' >> ~/.bashrc
          source ~/.bashrc
          chef exec kitchen test